# Generated by Django 3.1.6 on 2021-02-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0004_auto_20210207_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='title',
            new_name='name',
        ),
    ]
